### PR TITLE
Path cleanup and git integration 

### PR DESCRIPTION
**Pull request by mackerson**
I've gone ahead and cleaned up a lot of the pwd stuff, although some of it still needs to be sorted out. I've got more changes to make but we should discuss how you're calling this and what your work flow looks like. It will also pull down the latest stable build off of github now if you don't supply it a local copy. Make sure to check out config.json.example prior to running the script to provide it your local paths.

### CODE REVIEW

**Comment by mackerson** [comment]
The `node_modules` directory isn't generally kept under version control because it's kind of a gigantic recursive nightmare that produces [stuff like this](https://github.com/gthayer/Gulp-Task-Runners/tree/master/node_modules/gulp-livereload/node_modules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/camelcase-keys/node_modules/camelcase). So it's become a best practice to [keep it out of the repo](https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git). This also makes it so folks who are using the project simply have to `git clone` the directory, or download a zip and then run `npm install` so that you can draw from your local package cache rather then have to download all the files again, and you can make sure you also get the exact revisions of the libraries the project needs.  Here I've tried to preserve the initial structure of the project, since you're using it, however I think I'd generally recommend something along the lines of: 

For each new WordPress install you'd like to set up run: `git clone https://github.com/gthayer/Gulp-Task-Runners install_folder_name` to pull down the project. We could actually consider adding WordPress as a submodule, so by cloning the repo you get a fresh copy of whatever the latest stable is in one step. 

`npm install` to install the dependencies. This means each new WordPress project could have different node dependencies.

`gulp buildinstall` to configure the fresh install of WordPress. Some of the config stuff we could stash in the config.json so it's portable between installs, and to facilitate reuse between projects. We can also use it to store the path to whatever the theme directory is. 

I was going to use del to clean out the .git directory from inside of WordPress after I'd cloned it, since with the history it was around ~120mb, but it turned out to be easier to use a shallow clone and I forgot to remove it. I'll remove it. 

That is slightly different than how you've got it set up currently and are currently using it, but it fall closer in line with how a couple of other packages for WordPress using npm are handling their setup.

**Comment by gthayer** [comment]
Thanks. I researched your changes post-fact, and they make a lot of sense. I'll be merging your PR sometime today or tomorrow. Initially I built this for just myself, but I'm starting to see a wider potential. I'll be giving you commit access too, so feel free to keep playing with it.

I found a couple cross platform issues between windows and unix related to PWD. I've got a fix locally. A separate issue I've found on my linux computer, `npm install` adds 209 folders to `node_modules`, however on Windows the command only adds the needed files. Have you ever seen this? The program works fine, but all the files seem unnecessary.

**Comment by mackerson** [comment]
Sounds good! Yeah, I agree. My workflow always involves setting up a new install per project I work on, so I think there is definitely a place for a tool to jumpstart and automate that process. Need to come up with a catchy name and figure out what our project goals are. 

With regards to the `node_modules` directory on windows, it's a [known issue] (https://github.com/nodejs/node-v0.x-archive/issues/6960) and the source of a lot of vitriol. I'm honestly not sure if Windows file properties can correctly parse the deep directory tree - explorer can't delete it because it's too deep. That is why I tend to wind up installing [rimraf] (https://github.com/isaacs/rimraf) globally when I'm working on windows. I pulled down the main branch on my windows box and it showed the directory containing ~980 folders. How many do you see?

**Comment by gthayer** [comment]
I might not have been clear enough earlier. The extra folders are being created on Linux, not Windows. Here's the folder listing:

```ansi-regex
ansi-styles
any-shell-escape
archy
array-differ
array-union
array-uniq
arrify
asset-builder
async
balanced-match
beeper
binaryextensions
body-parser
brace-expansion
builtin-modules
bytes
camelcase
camelcase-keys
chalk
cli-color
clone
clone-stats
concat-map
content-type
core-util-is
dateformat
debug
defaults
del
depd
deprecated
duplexer
duplexer2
duplexify
ee-first
end-of-stream
error-ex
es5-ext
escape-string-regexp
event-emitter
event-stream
extend
fancy-log
faye-websocket
find-index
find-up
findup-sync
first-chunk-stream
flagged-respawn
from
gaze
get-stdin
glob
glob2base
globby
glob-stream
globule
glob-watcher
glogg
graceful-fs
gulp
gulp-compass
gulp-folders
gulp-git
gulp-livereload
gulplog
gulp-prompt
gulp-replace
gulp-util
has-ansi
has-gulplog
hosted-git-info
http-errors
iconv-lite
indent-string
inflight
inherits
inquirer
interpret
is-absolute
isarray
is-arrayish
is-builtin-module
is-finite
is-path-cwd
is-path-in-cwd
is-path-inside
is-relative
istextorbinary
is-utf8
liftoff
livereload-js
load-json-file
lodash
lodash.assign
lodash._baseassign
lodash._basecopy
lodash._basetostring
lodash._basevalues
lodash._bindcallback
lodash._createassigner
lodash.escape
lodash._getnative
lodash.isarguments
lodash.isarray
lodash._isiterateecall
lodash.keys
lodash._reescape
lodash._reevaluate
lodash._reinterpolate
lodash.restparam
lodash.template
lodash.templatesettings
loud-rejection
lru-cache
main-bower-files
map-obj
map-stream
media-typer
memoizee
meow
merge-stream
mime-db
mime-types
mini-lr
minimatch
minimist
mkdirp
ms
multimatch
multipipe
mute-stream
next-tick
normalize-package-data
number-is-nan
object-assign
object-path
once
on-finished
orchestrator
ordered-read-streams
os-homedir
parse-json
parseurl
path-exists
path-is-absolute
path-is-inside
path-type
pause-stream
pify
pinkie
pinkie-promise
pretty-hrtime
print.txt
process-nextick-args
qs
raw-body
readable-stream
read-pkg
read-pkg-up
rechoir
redent
repeating
replace-ext
replacestream
require-dir
resolve
rimraf
semver
sequencify
sigmund
signal-exit
sparkles
spdx-correct
spdx-exceptions
spdx-expression-parse
spdx-license-ids
split
statuses
stream-combiner
stream-consume
string_decoder
strip-ansi
strip-bom
strip-indent
strip-json-comments
supports-color
textextensions
through
through2
through2-filter
tildify
traverse
trim-newlines
type-is
unique-stream
unpipe
user-home
util-deprecate
v8flags
validate-npm-package-license
vinyl
vinyl-fs
websocket-driver
websocket-extensions
which
wrappy
xtend```

**Comment by mackerson** [comment]
Okay, after scratching my head at this for a couple of minutes, I think I see what is going on and I've been able to reproduce it. Can you give me the versions of NPM you're running? NPM 2.11.3 produces a node_modules folder with a couple of primary dependency folders with their sub-dependencies listed below them, while 3.5.1 looks like it has a new directory structure for the node_modules directory where things are much more flat. You can check with `npm --version`

**Comment by gthayer** [comment]
3.3.10

**Comment by mackerson** [comment]
Okay, yep looks like this is par for the course in 3x, and it's because they're trying to flatten the tree: http://stackoverflow.com/questions/33649913/change-in-node-modules-folder-structure

**Pull request merged**
